sector_keywords = {
"INFORMATION-TECHNOLOGY": ["Python", "Java", "C++", "JavaScript", "Machine Learning", "AI", "Data Science", "Cloud", "Networking", "DevOps", "Cybersecurity", "Web Development", "Software Testing", "Database Management", "System Design", "Blockchain", "Microservices", "API Development", "Computer Vision", "Natural Language Processing", "Big Data", "Docker", "Kubernetes", "Serverless Computing", "CI/CD", "Agile Methodologies"],
"BUSINESS-DEVELOPMENT": ["Lead Generation", "Market Research", "Negotiation", "Sales Strategy", "CRM", "Networking", "Pitching", "Client Acquisition", "Partnerships", "Business Strategy", "Revenue Growth", "Account Management", "Market Expansion", "Customer Retention", "Sales Analytics"],
"ACCOUNTANT": ["Accounting", "Bookkeeping", "Financial Analysis", "Taxation", "Auditing", "Payroll", "Budgeting", "Financial Reporting", "Accounts Payable", "Accounts Receivable", "Forensic Accounting", "Cost Accounting", "Financial Forecasting", "Investment Analysis", "Risk Management"],
"ADVOCATE": ["Legal Research", "Litigation", "Contract Drafting", "Case Management", "Client Counseling", "Legal Writing", "Court Procedures", "Criminal Law", "Civil Law", "Intellectual Property", "Corporate Law", "Family Law", "Dispute Resolution", "Arbitration"],
"ENGINEERING": ["Mechanical Design", "Electrical Systems", "CAD", "MATLAB", "Project Management", "Structural Analysis", "Quality Control", "Robotics", "Automation", "3D Printing", "Control Systems", "Circuit Design", "Finite Element Analysis", "Thermodynamics"],
"CHEF": ["Culinary Skills", "Menu Planning", "Food Safety", "Recipe Development", "Kitchen Management", "Catering", "Plating", "Baking", "Pastry Making", "Molecular Gastronomy", "Food Presentation", "Cost Control", "Inventory Management"],
"FITNESS": ["Personal Training", "Nutrition", "Strength Training", "Cardio", "Client Assessment", "Weight Loss", "Fitness Coaching", "Sports Nutrition", "Bodybuilding", "Flexibility Training", "Injury Prevention", "Functional Training", "Group Training"],
"FINANCE": ["Investment Analysis", "Financial Modeling", "Portfolio Management", "Risk Management", "Capital Markets", "Budgeting", "Corporate Finance", "Mergers & Acquisitions", "Financial Planning", "Treasury Management", "Valuation", "Private Equity", "Venture Capital"],
"SALES": ["Lead Generation", "Customer Acquisition", "Sales Strategy", "CRM", "Negotiation", "Market Research", "Client Management", "Cross-Selling", "Upselling", "Cold Calling", "Inside Sales", "Field Sales", "Sales Forecasting"],
"AVIATION": ["Flight Operations", "Aircraft Maintenance", "Air Traffic Control", "Pilot Training", "Flight Safety", "Navigation", "Cabin Crew Training", "Flight Simulation", "Aerospace Engineering", "Weather Analysis", "Aviation Safety", "Ground Handling", "Airport Operations"],
"HEALTHCARE": ["Patient Care", "Medical Terminology", "Clinical Research", "Healthcare Management", "Diagnostics", "Nursing", "Surgery", "Pharmacy", "Medical Equipment Handling", "Telemedicine", "Emergency Medicine", "Medical Billing", "Medical Coding"],
"CONSULTANT": ["Business Strategy", "Market Analysis", "Problem Solving", "Client Communication", "Project Management", "Data Analysis", "Change Management", "Process Improvement", "Business Transformation", "Stakeholder Management", "Organizational Development"],
"BANKING": ["Financial Analysis", "Customer Service", "Risk Assessment", "Loan Processing", "Wealth Management", "Investment Banking", "Retail Banking", "Credit Analysis", "Fraud Detection", "Financial Planning", "Banking Operations", "Regulatory Compliance"],
"CONSTRUCTION": ["Project Management", "Blueprint Reading", "Site Supervision", "Safety Management", "Cost Estimation", "Structural Analysis", "Welding", "Masonry", "Plumbing", "Electrical Systems", "HVAC Systems", "Land Surveying", "Building Codes"],
"PUBLIC-RELATIONS": ["Media Relations", "Crisis Management", "Brand Communication", "Content Creation", "Event Planning", "Social Media", "Press Release Writing", "Crisis Communication", "Reputation Management", "Media Training", "Speech Writing"],
"HR": ["Recruitment", "Employee Relations", "Performance Management", "Payroll", "Onboarding", "Employee Engagement", "HR Compliance", "Training & Development", "Conflict Resolution", "Compensation & Benefits", "Talent Acquisition"],
"DESIGNER": ["Graphic Design", "UI/UX", "Typography", "Branding", "Adobe Suite", "Illustration", "Animation", "3D Modeling", "Web Design", "User Research", "Prototyping", "Product Design", "Motion Graphics"],
"ARTS": ["Painting", "Drawing", "Sculpting", "Photography", "Art History", "Creativity", "Design Thinking", "Art Curation", "Installation Art", "Mixed Media", "Visual Arts", "Art Direction", "Printmaking"],
"TEACHER": ["Lesson Planning", "Curriculum Development", "Student Assessment", "Classroom Management", "Education Technology", "Special Education", "Online Teaching", "Student Counseling", "Pedagogy", "Educational Psychology", "Instructional Design"],
"APPAREL": ["Fashion Design", "Textile Knowledge", "Pattern Making", "Fashion Trends", "Merchandising", "Brand Development", "Sewing", "Draping", "Fashion Illustration", "Fabric Selection", "Trend Forecasting", "Costume Design"],
"DIGITAL-MEDIA": ["Content Creation", "Social Media Marketing", "SEO", "Video Editing", "Influencer Marketing", "Digital Strategy", "Digital Advertising", "Web Analytics", "Podcasting", "Email Marketing", "Search Engine Marketing"],
"AGRICULTURE": ["Crop Management", "Soil Analysis", "Irrigation", "Sustainable Farming", "Pest Control", "Agricultural Technology", "Organic Farming", "Agroforestry", "Soil Health", "Greenhouse Management", "Precision Agriculture"],
"AUTOMOBILE": ["Automotive Design", "Vehicle Maintenance", "Quality Control", "Manufacturing", "Mechanical Systems", "Automotive Electronics", "Vehicle Dynamics", "CAD/CAM", "Electric Vehicles", "Automotive Testing"],
"BPO": ["Customer Service", "Communication Skills", "Data Entry", "Process Optimization", "Multitasking", "Technical Support", "Voice Process", "Non-Voice Process", "Back Office Operations", "Client Support", "Call Center Operations"]
}


degrees = [
    "Bachelor of Technology (B.Tech)", "B.Tech", "B. Tech", "BTech", "Bachelor of Technology", 
    "Bachelor of Technology (B. Tech)", "B. Tech", "BTech", "B.Tech", "Bachelor of Technology", 
    "Master of Technology (M.Tech)", "M.Tech", "M. Tech", "MTech", 
    "Master of Technology", "M. Tech", "MTech", "MTech Degree", 
    "Bachelor of Science (B.Sc)", "B.Sc", "BSc", "B.S.", "BSc Hons", "B.Sc Hons", 
    "Bachelor of Science", "B.Sc Degree", "B.Sc Hons Degree",
    "Master of Science (M.Sc)", "M.Sc", "MSc", "M.S.", 
    "Master of Science", "M.Sc Degree", "M.Sc Hons", 
    "Diploma", "Dipl.", "Diploma Degree", 
    "Bachelor of Engineering (B.E)", "B.E", "BEng", "Bachelor of Engineering", 
    "B.E Degree", "BEng Degree", 
    "Master of Engineering (M.E)", "M.E", "MEng", "Master of Engineering", 
    "M.E Degree", "MEng Degree", 
    "Bachelor of Computer Applications (BCA)", "BCA", "BCA Degree", 
    "Master of Computer Applications (MCA)", "MCA", "MCA Degree", 
    "Bachelor of Commerce (B.Com)", "B.Com", "BCom", "BCom Degree", 
    "Master of Commerce (M.Com)", "M.Com", "MCom", "MCom Degree", 
    "Bachelor of Arts (BA)", "BA", "B.A.", "BA Degree", 
    "Master of Arts (MA)", "MA", "M.A.", "MA Degree", 
    "Bachelor of Business Administration (BBA)", "BBA", "BBA Degree", 
    "Master of Business Administration (MBA)", "MBA", "MBA Degree", 
    "Bachelor of Pharmacy (B.Pharm)", "B.Pharm", "BPharm", "BPharm Degree", 
    "Master of Pharmacy (M.Pharm)", "M.Pharm", "MPharm", "MPharm Degree", 
    "Bachelor of Dental Surgery (BDS)", "BDS", "BDS Degree", 
    "Master of Dental Surgery (MDS)", "MDS", "MDS Degree", 
    "Bachelor of Medicine and Bachelor of Surgery (MBBS)", "MBBS", "MBBS Degree", 
    "Doctor of Medicine (MD)", "MD", "MD Degree", 
    "Bachelor of Homoeopathic Medicine and Surgery (BHMS)", "BHMS", "BHMS Degree", 
    "Bachelor of Ayurvedic Medicine and Surgery (BAMS)", "BAMS", "BAMS Degree", 
    "Bachelor of Physiotherapy (BPT)", "BPT", "BPT Degree", 
    "Master of Physiotherapy (MPT)", "MPT", "MPT Degree", 
    "Bachelor of Fine Arts (BFA)", "BFA", "BFA Degree", 
    "Master of Fine Arts (MFA)", "MFA", "MFA Degree", 
    "Bachelor of Laws (LLB)", "LLB", "LLB Degree", 
    "Master of Laws (LLM)", "LLM", "LLM Degree", 
    "Bachelor of Architecture (B.Arch)", "B.Arch", "BArch", "B.Arch Degree",
    "Master of Architecture (M.Arch)", "M.Arch", "MArch", "M.Arch Degree", 
    "Bachelor of Education (B.Ed)", "B.Ed", "B.Ed Degree", 
    "Master of Education (M.Ed)", "M.Ed", "M.Ed Degree", 
    "Bachelor of Science (Hons)", "B.Sc (Hons)", "BSc (Hons)", "BSc Hons", "B.Sc Hons", 
    "Master of Science (Hons)", "M.Sc (Hons)", "M.Sc Hons", "MSc Hons", 
    "Bachelor of Science in Information Technology (B.Sc IT)", "B.Sc IT", "BSc IT", 
    "Master of Science in Information Technology (M.Sc IT)", "M.Sc IT", "MSc IT"
]
general_skills = ["Communication", "Time Management", "Teamwork", "Problem Solving", "Leadership", "Critical Thinking", "Adaptability", "Creativity", "Organization", "Interpersonal Skills", "Attention to Detail", "Emotional Intelligence", "Project Management", "Decision Making", "Negotiation", "Networking", "Presentation Skills", "Work Ethic", "Conflict Resolution", "Collaboration", "Research", "Customer Service", "Multitasking", "Data Analysis", "Business Strategy"]